abstract class Databases {
  static List<Map<String, dynamic>> products = [
    {
      'image': 'img1.jpg',
      'name': 'Stylish Chair',
      'city': 'New York',
      'price': '\$150',
      'islike': false,
    },
    {
      'image': 'img2.jpg',
      'name': 'Modern Sofa',
      'city': 'Los Angeles',
      'price': '\$800',
      'islike': false,
    },
    {
      'image': 'img3.jpg',
      'name': 'Wooden Table',
      'city': 'Chicago',
      'price': '\$250',
      'islike': false,
    },
    {
      'image': 'img4.jpg',
      'name': 'Cozy Bed',
      'city': 'Houston',
      'price': '\$450',
      'islike': false,
    },
    {
      'image': 'img5.jpg',
      'name': 'Elegant Lamp',
      'city': 'Phoenix',
      'price': '\$60',
      'islike': false,
    },
    {
      'image': 'img6.jpg',
      'name': 'Leather Armchair',
      'city': 'Philadelphia',
      'price': '\$300',
      'islike': false,
    },
    {
      'image': 'img7.jpg',
      'name': 'Bookshelf',
      'city': 'San Antonio',
      'price': '\$120',
      'islike': false,
    },
    {
      'image': 'img8.jpg',
      'name': 'Dining Set',
      'city': 'San Diego',
      'price': '\$600',
      'islike': false,
    },
    {
      'image': 'img9.jpg',
      'name': 'Office Desk',
      'city': 'Dallas',
      'price': '\$200',
      'islike': false,
    },
    {
      'image': 'img10.jpg',
      'name': 'Kitchen Island',
      'city': 'San Jose',
      'price': '\$350',
      'islike': false,
    },
    {
      'image': 'img11.jpg',
      'name': 'Outdoor Bench',
      'city': 'Austin',
      'price': '\$180',
      'islike': false,
    },
    {
      'image': 'img12.jpg',
      'name': 'Patio Set',
      'city': 'Jacksonville',
      'price': '\$400',
      'islike': false,
    },
    {
      'image': 'img13.jpg',
      'name': 'Recliner',
      'city': 'Fort Worth',
      'price': '\$220',
      'islike': false,
    },
    {
      'image': 'img14.jpg',
      'name': 'Bar Stool',
      'city': 'Columbus',
      'price': '\$90',
      'islike': false,
    },
    {
      'image': 'img15.jpg',
      'name': 'Wardrobe',
      'city': 'Charlotte',
      'price': '\$500',
      'islike': false,
    },
    {
      'image': 'img16.jpg',
      'name': 'Coffee Table',
      'city': 'San Francisco',
      'price': '\$130',
      'islike': false,
    },
    {
      'image': 'img17.jpg',
      'name': 'TV Stand',
      'city': 'Indianapolis',
      'price': '\$170',
      'islike': false,
    },
    {
      'image': 'img18.jpg',
      'name': 'Nightstand',
      'city': 'Seattle',
      'price': '\$80',
      'islike': false,
    },
    {
      'image': 'img19.jpg',
      'name': 'Shoe Rack',
      'city': 'Denver',
      'price': '\$70',
      'islike': false,
    },
    {
      'image': 'img20.jpg',
      'name': 'Dresser',
      'city': 'Washington',
      'price': '\$280',
      'islike': false,
    },
    {
      'image': 'img21.jpg',
      'name': 'Vanity',
      'city': 'Boston',
      'price': '\$300',
      'islike': false,
    },
    {
      'image': 'img22.jpg',
      'name': 'Bedside Lamp',
      'city': 'El Paso',
      'price': '\$40',
      'islike': false,
    },
    {
      'image': 'img23.jpg',
      'name': 'Floor Lamp',
      'city': 'Detroit',
      'price': '\$110',
      'islike': false,
    },
    {
      'image': 'img24.jpg',
      'name': 'Ottoman',
      'city': 'Nashville',
      'price': '\$150',
      'islike': false,
    },
    {
      'image': 'img25.jpg',
      'name': 'Bean Bag',
      'city': 'Portland',
      'price': '\$100',
      'islike': false,
    },
    {
      'image': 'img26.jpg',
      'name': 'Rocking Chair',
      'city': 'Memphis',
      'price': '\$160',
      'islike': false,
    },
    {
      'image': 'img27.jpg',
      'name': 'Folding Table',
      'city': 'Oklahoma City',
      'price': '\$80',
      'islike': false,
    },
    {
      'image': 'img28.jpg',
      'name': 'Loveseat',
      'city': 'Las Vegas',
      'price': '\$400',
      'islike': false,
    },
    {
      'image': 'img29.jpg',
      'name': 'Hall Tree',
      'city': 'Louisville',
      'price': '\$210',
      'islike': false,
    },
    {
      'image': 'img30.jpg',
      'name': 'Console Table',
      'city': 'Baltimore',
      'price': '\$190',
      'islike': false,
    },
    {
      'image': 'img31.jpg',
      'name': 'Sectional Sofa',
      'city': 'Milwaukee',
      'price': '\$900',
      'islike': false,
    },
    {
      'image': 'img32.jpg',
      'name': 'Armoire',
      'city': 'Albuquerque',
      'price': '\$550',
      'islike': false,
    },
    {
      'image': 'img33.jpg',
      'name': 'Chaise Lounge',
      'city': 'Tucson',
      'price': '\$300',
      'islike': false,
    },
    {
      'image': 'img34.jpg',
      'name': 'Bunk Bed',
      'city': 'Fresno',
      'price': '\$350',
      'islike': false,
    },
    {
      'image': 'img35.jpg',
      'name': 'Futon',
      'city': 'Sacramento',
      'price': '\$250',
      'islike': false,
    },
    {
      'image': 'img36.jpg',
      'name': 'Corner Desk',
      'city': 'Kansas City',
      'price': '\$220',
      'islike': false,
    },
    {
      'image': 'img37.jpg',
      'name': 'Hutch',
      'city': 'Long Beach',
      'price': '\$280',
      'islike': false,
    },
    {
      'image': 'img38.jpg',
      'name': 'Chaise',
      'city': 'Mesa',
      'price': '\$400',
      'islike': false,
    },
    {
      'image': 'img39.jpg',
      'name': 'Buffet Table',
      'city': 'Atlanta',
      'price': '\$330',
      'islike': false,
    },
    {
      'image': 'img40.jpg',
      'name': 'TV Console',
      'city': 'Colorado Springs',
      'price': '\$200',
      'islike': false,
    },
    {
      'image': 'img41.jpg',
      'name': 'Sideboard',
      'city': 'Virginia Beach',
      'price': '\$350',
      'islike': false,
    },
    {
      'image': 'img42.jpg',
      'name': 'Entryway Bench',
      'city': 'Raleigh',
      'price': '\$150',
      'islike': false,
    },
    {
      'image': 'img43.jpg',
      'name': 'Trundle Bed',
      'city': 'Omaha',
      'price': '\$400',
      'islike': false,
    },
    {
      'image': 'img44.jpg',
      'name': 'Secretary Desk',
      'city': 'Miami',
      'price': '\$300',
      'islike': false,
    },
    {
      'image': 'img45.jpg',
      'name': 'Accent Chair',
      'city': 'Oakland',
      'price': '\$200',
      'islike': false,
    },
    {
      'image': 'img46.jpg',
      'name': 'Writing Desk',
      'city': 'Minneapolis',
      'price': '\$180',
    }
  ];
}
